export const quizData = [
  // Section 1: Forecasting Basics
  {
    id: "q1",
    question: "Which of the following is NOT a type of qualitative forecasting method?",
    options: {
      A: "Delphi Method",
      B: "Brainstorming",
      C: "Time Series",
      D: "Expert Opinion",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q2",
    question: "What does MAD stand for in forecasting metrics?",
    options: {
      A: "Mean Autocorrelation Deviation",
      B: "Mean Absolute Deviation",
      C: "Median Actual Difference",
      D: "Maximum Absolute Distance",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q3",
    question: "In forecasting, a horizontal time series implies:",
    options: {
      A: "A cyclical pattern",
      B: "A trend with upward direction",
      C: "Stationarity in its mean",
      D: "Seasonal variation",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q4",
    question: "Which metric provides a measure of squared forecast error?",
    options: {
      A: "MAD",
      B: "MWAD",
      C: "MSD",
      D: "Covariance",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q5",
    question: "What is the correlation coefficient value range?",
    options: {
      A: "0 to 1",
      B: "-1 to 1",
      C: "0 to ∞",
      D: "-∞ to ∞",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q6",
    question: "Which of the following is NOT a typical step in the forecasting process?",
    options: {
      A: "Clean the data",
      B: "Conduct an employee survey",
      C: "Choose an appropriate model",
      D: "Perform exploratory analysis",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q7",
    question: "The main difference between qualitative and quantitative forecasting is that:",
    options: {
      A: "Quantitative uses expert opinions",
      B: "Qualitative uses numerical models",
      C: "Quantitative uses historical data",
      D: "Qualitative is more accurate",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q8",
    question: "One of the steps in the forecasting process is cleaning the data to remove inconsistencies.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q9",
    question: "Quantitative forecasting requires historical numerical data to be effective.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q10",
    question:
      "Covariance and correlation coefficient are used to measure the extent of the linear relationship between two variables and can help identify explanatory relationships.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },

  // Section 2: Error Metrics
  {
    id: "q11",
    question: "Which of the following is the correct formula for the Akaike Information Criterion (AIC)?",
    options: {
      A: "AIC = 2k - 2log(L)",
      B: "AIC = log(L) + k",
      C: "AIC = -2log(L) + 2k",
      D: "AIC = -log(L) + 2k",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q12",
    question: "A forecasting model gives ME = 0 but MSE > 0. What does this imply?",
    options: {
      A: "The model is perfect.",
      B: "The model consistently under-forecasts.",
      C: "The model has zero bias but some variability.",
      D: "The model consistently over-forecasts.",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q13",
    question: "Which of the following error metrics penalizes larger errors more heavily?",
    options: {
      A: "MAE",
      B: "ME",
      C: "MAPE",
      D: "MSE",
    },
    correctAnswer: "D",
    type: "mcq" as const,
  },
  {
    id: "q14",
    question: "For 3X3MA, what is the weight assigned to Y₀?",
    options: {
      A: "1/5",
      B: "3/9",
      C: "1/9",
      D: "2/9",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q15",
    question: "Which of the following is NOT a correct assumption for computing prediction intervals using MSE?",
    options: {
      A: "E(error) = 0",
      B: "Variance of error is fixed",
      C: "Errors follow Poisson distribution",
      D: "Errors are normally distributed",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q16",
    question: "Which of the following is true about the correlogram in time series analysis?",
    options: {
      A: "It plots residual errors against time",
      B: "It is used to visualize seasonality",
      C: "It plots autocorrelation against lag",
      D: "It identifies data outliers",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q17",
    question: "What is the main advantage of using U-statistics over MSE or MAE alone?",
    options: {
      A: "It ignores forecast bias",
      B: "It penalizes small errors",
      C: "It compares a model to a naive forecast",
      D: "It eliminates the need for residual analysis",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q18",
    question: "The Mean Error (ME) gives a good indication of the size of typical forecasting errors.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },
  {
    id: "q19",
    question: "MAPE (Mean Absolute Percentage Error) can be misleading when used for temperature data.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q20",
    question: "The Mean Squared Error (MSE) gives more weight to small errors than large ones.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },

  // Section 3: Simple Exponential Smoothing
  {
    id: "q21",
    question: "Which of the following assumptions is TRUE for Simple Exponential Smoothing (SES)?",
    options: {
      A: "The data has a linear trend",
      B: "The data shows seasonal variation",
      C: "The data has no trend or seasonality",
      D: "The data is random with exponential growth",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q22",
    question: "In SES, what does α (alpha) represent?",
    options: {
      A: "Seasonal index",
      B: "Growth rate",
      C: "Time period",
      D: "Smoothing constant",
    },
    correctAnswer: "D",
    type: "mcq" as const,
  },
  {
    id: "q23",
    question: "If α = 1 in SES, the forecast becomes:",
    options: {
      A: "The average of all past data",
      B: "Equal to the last observed value",
      C: "Equal to the first observed value",
      D: "Equal to the trend component",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q24",
    question: "Formula for Exponential Smoothing (Single non-adaptive parameter)",
    options: {
      A: "Ft+1 = Ft + a(Yt - Ft)",
      B: "Ft = a(Yt - Ft)",
      C: "Ft+1 = a(Yt - Ft)",
      D: "Ft = Ft + a(Yt - Ft)",
    },
    correctAnswer: "A",
    type: "mcq" as const,
  },
  {
    id: "q25",
    question: "Which of the following methods accounts for both level and trend in time series forecasting?",
    options: {
      A: "Simple Exponential Smoothing",
      B: "Holt's Linear Exponential Smoothing",
      C: "Moving Average",
      D: "Linear Regression",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q26",
    question:
      "Given the forecast data with α = 0.5, what will be the forecast for June, i.e., F(June, 0.5)? (Using: F(May)=189.4, Y(May)=310)",
    options: {
      A: "249.7",
      B: "205.6",
      C: "189.4",
      D: "310.0",
    },
    correctAnswer: "A",
    type: "mcq" as const,
  },
  {
    id: "q27",
    question: "In multiple non-adaptive exponential smoothing, the weights α₁, α₂, α₃, α₄ must sum to 1.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q28",
    question: "The initial forecast value F₁ is typically assumed to be 0",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },
  {
    id: "q29",
    question: "Exponential smoothing methods are appropriate for time series data with strong seasonality and trend.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },

  // Section 4: Moving Averages and Practical Examples
  {
    id: "q30",
    question: "The monthly demand forecast for June using a 3-month moving average (Given: 120, 90, 100, 75, 110) is?",
    options: {
      A: "97",
      B: "96",
      C: "95",
      D: "94",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q31",
    question:
      "The monthly demand forecast for February using Exponential Smoothing with a 40% weightage to Forecast value of January and 60% weightage to actual value of February is? (F(Jan)=120, Y(Feb)=90)",
    options: {
      A: "100",
      B: "101",
      C: "102",
      D: "103",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q32",
    question:
      "Use a TWO month moving average to generate a forecast for demand in month 6 (Demand: 23, 37, 29, 33, 27 in 10,000 units)",
    options: {
      A: "3,00,000",
      B: "3,00,030",
      C: "3,00,300",
      D: "3,03,000",
    },
    correctAnswer: "A",
    type: "mcq" as const,
  },
  {
    id: "q33",
    question:
      "Apply Exponential Smoothing with a smoothing constant of 0.5 to generate forecast for month 6 (Demand: 33, 27, 39, 23, 37 in 10,000 units)",
    options: {
      A: "3,00,288",
      B: "3,02,088",
      C: "3,20,880",
      D: "3,28,800",
    },
    correctAnswer: "D",
    type: "mcq" as const,
  },
  {
    id: "q34",
    question:
      "Which of the following methods uses only the previous period's actual value for forecasting the next period?",
    options: {
      A: "5-month moving average",
      B: "Naïve method",
      C: "Weighted moving average",
      D: "Holt's linear method",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q35",
    question: "Which of the following is true for trend-adjusted exponential smoothing?",
    options: {
      A: "It uses one smoothing parameter α",
      B: "It does not account for trend",
      C: "It uses both α and β parameters",
      D: "It ignores previous forecasts",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q36",
    question: "The main objective in selecting values for α and β in Holt's method is to:",
    options: {
      A: "Minimize forecasted values",
      B: "Minimize the sum of squared errors",
      C: "Maximize mean forecast error",
      D: "Equalize trend and level",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q37",
    question: "A simple 5-month moving average gives more weight to recent data than older data.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },
  {
    id: "q38",
    question: "The mean squared error (MSE) can be used to compare the accuracy of different forecasting methods.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q39",
    question: "Multiple adaptive exponential smoothing uses only one smoothing constant to calculate forecasts.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },

  // Section 5: Holt-Winters Method
  {
    id: "q40",
    question: "In Holt-Winters method, m refers to:",
    options: {
      A: "The smoothing parameter for level",
      B: "Number of seasonal periods",
      C: "Forecast horizon in time periods ahead",
      D: "Number of data points in one season",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q41",
    question: "In Holt-Winters multiplicative seasonality, seasonality is incorporated by:",
    options: {
      A: "Addition and subtraction",
      B: "Multiplication and division",
      C: "Squaring and rooting",
      D: "Using only addition",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q42",
    question: "The parameter β in Holt-Winters method is associated with:",
    options: {
      A: "Level",
      B: "Trend",
      C: "Seasonality",
      D: "Forecast horizon",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q43",
    question: "In Holt-Winters additive seasonality method, the level equation is:",
    options: {
      A: "Lt=α(Yt−St−s)+(1−α)(Lt−1+bt−1)",
      B: "Lt=α(Yt/St−s)+(1−α)(Lt−1+bt−1)",
      C: "Lt=α(Yt)+(1−α)(Lt−1+bt−1)",
      D: "Lt=Yt−St−s",
    },
    correctAnswer: "A",
    type: "mcq" as const,
  },
  {
    id: "q44",
    question: "Which statement is incorrect about Holt-Winters forecasting?",
    options: {
      A: "α, β, and γ are smoothing parameters",
      B: "These parameters are chosen to minimize the sum of squared errors",
      C: "Additive model is preferred when seasonal variations are proportional to level",
      D: "Multiplicative model is used when seasonal variations change with the level",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q45",
    question: "In Holt-Winters method, the length of seasonality 's' represents:",
    options: {
      A: "The total number of data points",
      B: "The number of observations in one complete seasonal cycle",
      C: "The smoothing parameter for level",
      D: "The time ahead for forecasting",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q46",
    question:
      "In both additive and multiplicative models, m represents the number of periods ahead for which we want the forecast.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },
  {
    id: "q47",
    question: "Holt-Winters method can only be applied to non-seasonal time series data.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },
  {
    id: "q48",
    question:
      "In Holt-Winters multiplicative seasonality, the seasonal factor remains constant regardless of the series level.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },

  // Section 6: Multiple Linear Regression Basics
  {
    id: "q49",
    question:
      "Which of the following is an assumption of Multiple Linear Regression (MLR) regarding exogeneity of the independent variables?",
    options: {
      A: "Disturbances have different variances at each observation.",
      B: "The expected value of the disturbance is independent of the independent variables.",
      C: "Independent variables must be random draws from a stochastic process.",
      D: "Disturbances are always normally distributed.",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q50",
    question: "Which of the following best describes the Full Rank (Assumption 2) in MLR?",
    options: {
      A: "No independent variable should be a perfect linear combination of others.",
      B: "Independent variables must have zero variance",
      C: "Error terms must be identically distributed.",
      D: "All independent variables must be normally distributed.",
    },
    correctAnswer: "A",
    type: "mcq" as const,
  },
  {
    id: "q51",
    question:
      "Which of the following assumptions in MLR ensures that the coefficients are uniquely estimable (no perfect collinearity)?",
    options: {
      A: "Linearity",
      B: "Exogeneity",
      C: "Homoscedasticity",
      D: "Full Rank",
    },
    correctAnswer: "D",
    type: "mcq" as const,
  },
  {
    id: "q52",
    question: "If in a regression model the correlation coefficient r=−1, what does this imply?",
    options: {
      A: "No relationship between x and y",
      B: "A perfect positive linear relationship",
      C: "A perfect negative linear relationship",
      D: "A nonlinear relationship",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q53",
    question: "Independent variables must always follow a normal distribution.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },
  {
    id: "q54",
    question:
      "In Multiple Linear Regression, the exogeneity assumption means that the error term is correlated with the independent variables.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },
  {
    id: "q55",
    question: "Positive correlation means that as one variable increases, the other also increases.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },

  // Section 7: CAPM and Financial Models
  {
    id: "q56",
    question: "Using the CAPM model, if Rf=6%, E(Rm)=12% and β=1.2, the expected return on the asset is:",
    options: {
      A: "12.0%",
      B: "13.2%",
      C: "14.4%",
      D: "15.0%",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q57",
    question: "In MLR, if the independent variables are orthogonal (uncorrelated):",
    options: {
      A: "The OLS estimators are biased",
      B: "The residuals are autocorrelated",
      C: "Heteroscedasticity is guaranteed",
      D: "The MLR slopes equal the slopes from individual SLRs",
    },
    correctAnswer: "D",
    type: "mcq" as const,
  },
  {
    id: "q58",
    question: "In the Capital Asset Pricing Model (CAPM), the slope of the capital market line represents:",
    options: {
      A: "The expected return on risk-free assets",
      B: "The price of risk",
      C: "The covariance between market and asset returns",
      D: "The market capitalization weights",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q59",
    question: "The Multiple Index Model is mainly used to:",
    options: {
      A: "Ignore economic influences beyond the market",
      B: "Capture non-market influences that affect securities",
      C: "Replace CAPM in all financial calculations",
      D: "Measure only market-based volatility",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q60",
    question: "In Multiple Linear Regression (MLR), homoscedasticity means:",
    options: {
      A: "The error terms have unequal variances",
      B: "The independent variables are correlated with the error term",
      C: "The error terms have equal and finite variances",
      D: "The independent variables have the same scale",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q61",
    question:
      "In Multiple Linear Regression, homoscedasticity means that the error terms have constant variance across observations.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q62",
    question: 'In CAPM, the slope of the Capital Market Line represents the "price of risk."',
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q63",
    question:
      "In the Multiple Index Model, non-market factors such as inflation or exchange rates can also influence stock returns.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },

  // Section 8: Advanced MLR
  {
    id: "q64",
    question:
      "In Multiple Linear Regression, SEL or OLS estimate (which is unique and minimizes the sum of square of residuals) of β is given as?",
    options: {
      A: "(X'X)^-1 X'Y",
      B: "(XX')^-1XY",
      C: "(X'X)^-1Y",
      D: "(X'X)^-1X",
    },
    correctAnswer: "A",
    type: "mcq" as const,
  },
  {
    id: "q65",
    question: "In regression analysis, the total sum of squares (SST) is decomposed as:",
    options: {
      A: "SST = SSR × SSE",
      B: "SST = SSR + SSE",
      C: "SST = SSE – SSR",
      D: "SST = SSR ÷ SSE",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q66",
    question: "The Linear Exponential (LINEX) Loss Function is useful when:",
    options: {
      A: "Losses for overestimation are larger than for underestimation.",
      B: "Losses for underestimation are larger than for overestimation.",
      C: "Losses are independent of error direction.",
      D: "None of the above.",
    },
    correctAnswer: "A",
    type: "mcq" as const,
  },
  {
    id: "q67",
    question:
      "In Multiple Linear Regression all the observations on X convey information about the expected value of the disturbance.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },
  {
    id: "q68",
    question:
      "For Multiple Linear Regression, if variance of the error term is not constant, then this property is known as heteroscedasticity.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q69",
    question:
      "For Multiple Linear Regression, disturbances that meet the twin assumptions of homoscedasticity and non-autocorrelation are sometimes called spherical disturbances.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },

  // Section 9: Loss Functions and Logistic Regression
  {
    id: "q70",
    question: "The LINEX loss function is asymmetric and penalizes errors differently. When a > 0, it penalizes:",
    options: {
      A: "Overestimation more heavily",
      B: "Underestimation more heavily",
      C: "Both equally",
      D: "Neither",
    },
    correctAnswer: "A",
    type: "mcq" as const,
  },
  {
    id: "q71",
    question: "In Multiple Linear Regression, the Balanced Loss Function (BLF) combines:",
    options: {
      A: "Only squared error loss",
      B: "Only LINEX loss",
      C: "Both squared error and LINEX losses with a weight parameter λ",
      D: "Logistic regression with squared error",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q72",
    question: "Which of the following represents the logit transformation in logistic regression?",
    options: {
      A: "ln{p}",
      B: "ln{1−p}",
      C: "ln{p/(1−p)}",
      D: "e^z",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q73",
    question:
      "In Logistic Regression, the sigmoid function is used to map logit values into probabilities. Which property is most critical?",
    options: {
      A: "It is linear in z.",
      B: "It maps real values into (0,1).",
      C: "It is convex.",
      D: "It always outputs 0.5.",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q74",
    question: "In logistic regression, if P(Y=1|x)=0.73, what does it indicate?",
    options: {
      A: "The model predicts negative sentiment.",
      B: "The model predicts positive sentiment.",
      C: "The model is inconclusive.",
      D: "The review has no sentiment words.",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q75",
    question:
      "In the Balanced Loss Function (BLF), SEL represents precision of estimation, while LINEX represents goodness of fit.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q76",
    question: "When λ = 0 in BLF, the risk reduces to only the LINEX loss component.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q77",
    question: "Logistic regression can be viewed as a simple neural network with no hidden layers.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },

  // Section 10: Non-linear Regression Models
  {
    id: "q78",
    question: "In the logarithmic regression model Y=θ₁+θ₂ ln(x)+ε, if θ₂<0, how does Y change with x?",
    options: {
      A: "Y increases",
      B: "Y decreases",
      C: "Y remains constant",
      D: "Y follows a random walk",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q79",
    question:
      "For the exponential regression model: Y=θ₁ e^(θ₂x) +ε. If θ₁=5, θ₂=−0.5, and x=2, what is the expected value of Y?",
    options: {
      A: "40.5",
      B: "2.5",
      C: "65.9",
      D: "80.0",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q80",
    question: "In the power regression model Y=θ₁x^(θ₂) + ε, if θ₂=0.5, then the curve is:",
    options: {
      A: "Linear",
      B: "Concave upward (square-root type)",
      C: "Convex upward (exponential type)",
      D: "Constant",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q81",
    question:
      "Which regression model among the following is suitable for limited growth where Y approaches a horizontal asymptote as x → ∞?",
    options: {
      A: "Polynomial",
      B: "Asymptotic",
      C: "Logistic",
      D: "Exponential",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q82",
    question: "For the logarithmic model: Y=θ₁+θ₂ ln(x), if θ₁=10, θ₂=4, and x=5, what is Y?",
    options: {
      A: "12.0",
      B: "14.4",
      C: "16.4",
      D: "18.4",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q83",
    question:
      "Which regression model is most suitable when growth is initially rapid but eventually stabilizes at a maximum value?",
    options: {
      A: "Logistic regression",
      B: "Exponential regression",
      C: "Asymptotic regression",
      D: "Polynomial regression",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q84",
    question: "The error term in all the regression models presented must follow only the normal distribution.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },
  {
    id: "q85",
    question: "Logistic regression always produces probabilities that lie strictly between 0 and 1.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q86",
    question: "The linear probability model ensures that all predicted probabilities are between 0 and 1.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },

  // Section 11: Time Series Analysis Basics
  {
    id: "q87",
    question: "A time series is defined as:",
    options: {
      A: "A random sample of cross-sectional data",
      B: "A set of observations recorded at specific time points",
      C: "A sequence of independent experiments",
      D: "A regression between dependent and independent variables",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q88",
    question: "Which of the following is not an application of time series analysis?",
    options: {
      A: "Sales forecasting",
      B: "Inventory control",
      C: "Prediction of financial data",
      D: "Multiple regression estimation",
    },
    correctAnswer: "D",
    type: "mcq" as const,
  },
  {
    id: "q89",
    question: "The main objectives of time series analysis include all except:",
    options: {
      A: "Description",
      B: "Modelling",
      C: "Forecasting",
      D: "Random sampling",
    },
    correctAnswer: "D",
    type: "mcq" as const,
  },
  {
    id: "q90",
    question: "A time series {Xt} is (weakly) stationary if:",
    options: {
      A: "Mean depends on time t",
      B: "Covariance depends only on lag h, not on t",
      C: "Variance increases with time",
      D: "It contains trend and seasonality",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q91",
    question: "The auto-covariance function (ACVF) of a stationary series at lag h is:",
    options: {
      A: "Cov(Xt+h, Xt)",
      B: "Var(Xt)",
      C: "Cor(Xt+h, Xt)",
      D: "E(Xt+h – Xt)",
    },
    correctAnswer: "A",
    type: "mcq" as const,
  },
  {
    id: "q92",
    question: "Slow decay of ACF values toward zero indicates:",
    options: {
      A: "Stationarity",
      B: "Non-stationarity with trend",
      C: "White noise process",
      D: "Independence of variables",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q93",
    question: "ARIMA(p,d,q) stands for:",
    options: {
      A: "Autoregression, Independence, Moving Average",
      B: "Autoregression, Integration, Moving Average",
      C: "Average, Regression, Integrated Mean Analysis",
      D: "Auto-Inference of Model Accuracy",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q94",
    question: "The main objectives of time series analysis include description, modelling, forecasting, and control.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q95",
    question:
      "In a stationary time series, covariance between observations depends only on the lag, not on the actual time.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q96",
    question: "If the ACF decays slowly toward zero, the time series is stationary.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "False",
    type: "trueFalse" as const,
  },

  // Section 12: Advanced Time Series (AR, MA, ARIMA)
  {
    id: "q97",
    question: "An AR(1) process becomes a random walk when:",
    options: {
      A: "|φ| < 1",
      B: "|φ| > 1",
      C: "φ = 1",
      D: "φ = 0",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q98",
    question: "The Partial Autocorrelation Function (PACF) is used to:",
    options: {
      A: "Identify order of MA(q) model",
      B: "Identify order of AR(p) model",
      C: "Measure volatility clustering",
      D: "Estimate mean squared error",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q99",
    question: "Which of the following models captures the leverage effect?",
    options: {
      A: "AR(1)",
      B: "MA(1)",
      C: "EGARCH / AGARCH",
      D: "Random Walk",
    },
    correctAnswer: "C",
    type: "mcq" as const,
  },
  {
    id: "q100",
    question: "The Ljung-Box-Pierce Q-Test is used to test for:",
    options: {
      A: "Stationarity",
      B: "Presence of autocorrelation",
      C: "Random walk property",
      D: "MLE efficiency",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q101",
    question: "If |φ| < 1 in AR(1), the process is:",
    options: {
      A: "Non-stationary",
      B: "Stationary",
      C: "Random Walk",
      D: "Explosive",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q102",
    question: "In MA(q) models, autocorrelation cuts off after:",
    options: {
      A: "p lags",
      B: "q lags",
      C: "infinite lags",
      D: "zero lags",
    },
    correctAnswer: "B",
    type: "mcq" as const,
  },
  {
    id: "q103",
    question: "Which estimation method uses Yule-Walker equations?",
    options: {
      A: "ARMA preliminary estimation",
      B: "Maximum likelihood estimation",
      C: "Burg's Algorithm",
      D: "EGARCH estimation",
    },
    correctAnswer: "A",
    type: "mcq" as const,
  },
  {
    id: "q104",
    question: "PACF is useful in identifying the order of AR models.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q105",
    question: "In ARCH(p) models, conditional variance depends on past squared errors.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
  {
    id: "q106",
    question: "GARCH models extend ARCH by including lagged conditional variances.",
    options: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    correctAnswer: "True",
    type: "trueFalse" as const,
  },
]
